### ISSUE TITLE
Mechanism for users to add label for "other" inputs

### ISSUE THREAD

**Issue by dahnag** [Mulligan-Fund/grant-calculator#37]
![screen shot 2018-03-12 at 9 24 28 pm](https://user-images.githubusercontent.com/32071209/37317540-cdd7f78a-263b-11e8-907e-ab123b029458.jpg)
The last input for each category is an "other", intended for users to be able to input activities that might not otherwise be reflected in the activities/inputs.

**Comment by dahnag** [comment]
@readywater - I don't see this in the UI.  What am I missing?

**Comment by readywater** [comment]
Those fields were added at the bottom with this in the yaml:

```
      -
        header: "Additional Hours"
        name: "additional"
        questions:
          - 
            label: Describe other activities
            dbfield: other_label
            desc: "What is the name for these other actvities?"
            type: text
          -
            label: Other activities
            dbfield: gm_reporting_other
            desc: "Fill in staff time for any other tasks not included above."
            type: peoplelist
```
